apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  # Estragégias de atualização dos pods
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  # type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name:  mongodb
          image:  mongo:4.2.8
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
