name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Instalando dependências
        run: |
          cd ./src
          rm -f package-lock.json
          npm install
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Executando testes da aplicação
        run: |
          cd ./src          
          npm run test
  
  docker:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2.3.0
        with:
          context: ./src
          tags: |
            victormagalhaes/api-produto:latest
            victormagalhaes/api-produto:${{github.run_number}}
          push: true
  CD:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          # Kubernetes Config
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - uses: actions/checkout@v2
      - name: Deploy API to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
           manifests: |
            Kubernetes/api/deployment.yaml
            Kubernetes/api/service.yaml
      - name: Deploy MONGODB to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
           manifest: |
            Kubernetes/mongodb/deployment.yaml
            Kubernetes/mongodb/service.yaml
